name: Client Pipeline
on:
  push:
    branches:
      - main
    paths:
      - 'client/**' # Trigger only when code is pushed inside the 'client' folder

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_BASE_URI: ${{ secrets.REACT_APP_BASE_URI }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: cd client && npm install

      - name: Build client
        run: |
          cd client
          npm run build

      - name: Deploy client
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./client/build # Make sur
        env:
          REACT_APP_BASE_URI: ${{ secrets.REACT_APP_BASE_URI }}
